sudo: required
services:
        - docker

before_install:
        - docker build -t saeedfarhang/docker-test-ci -f Dockerfile.dev .

sctipt:
        - docker run saeedfarhang/docker-test-ci yarn test --coverage --watchAll=false
