version: '3'
services:
        frontend:
                build: 
                        context: .
                        dockerfile: Dockerfile.dev
                ports:
                        - "3000:3000"
                volumes:
                        - /usr/node_modules
                        - .:/usr/app
